# Generated by Django 4.2.2 on 2023-06-16 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_address.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_ADDRESS_ADDRESS_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=64, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('second_last_name', models.CharField(blank=True, max_length=64, verbose_name='second_last name')),
                ('id_type', models.CharField(choices=[('CC', 'citizenship card'), ('BC', 'birth certificate'), ('ID', 'identity card'), ('PAS', 'passport'), ('FOID', "foreigner's identity card"), ('DLIC', "driver's license")], max_length=4, verbose_name='identification type')),
                ('identification', models.CharField(max_length=64, verbose_name='identification')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone')),
                ('address', django_address.fields.AddressField(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_ADDRESS_ADDRESS_MODEL, verbose_name='address')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
    ]
